update

diff --git a/webv b/webv
--- a/webv
+++ b/webv
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: webv,v 1.89 2017/04/20 07:43:00 fulford Exp fulford $
+# $Id: webv,v 1.90 2017/04/20 07:45:07 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/webv,v $
-# $Revision: 1.89 $
+# $Revision: 1.90 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -9,7 +9,7 @@
 ########################################################################
 cmd=`basename $0`
 syntax="$cmd: [-d] [-v] <id>|-V"
-ver=`echo "$Id: webv,v 1.89 2017/04/20 07:43:00 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: webv,v 1.90 2017/04/20 07:45:07 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-c) config=$2;shift 2;;
@@ -20,7 +20,7 @@ while [ $# -gt 0 ] ;do
 	esac
 done
 [ -z "$id" ]&&{ echo "syntax: $syntax" >&2;exit 1;}
-[ 'id -u' -eq 0 ]&&{echo "$cmd: Cannot run as root user.">&2;exit 1}
+[ `id -u` -eq 0 ] &&{echo "$cmd: Cannot run as root user.">&2;exit 1 }
 config=${config:-"/usr/local/etc/webv.cf"}
 [ -f "$config" ]||{ echo "$cmd: $config not found">&2;exit 1;}
 
