update

diff --git a/webv b/webv
--- a/webv
+++ b/webv
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: webv,v 1.96 2018/12/05 10:41:53 fulford Exp fulford $
+# $Id: webv,v 1.8 2019/01/08 09:29:34 fulford Exp $
 # $Source: /src/admin/usr/local/etc/RCS/webv,v $
-# $Revision: 1.96 $
+# $Revision: 1.8 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -9,60 +9,119 @@
 ########################################################################
 cmd=`basename $0`
 syntax="$cmd: [[-d] [-v] <id> [-C # ]] | -V"
-ver=`echo "$Id: webv,v 1.96 2018/12/05 10:41:53 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: webv,v 1.8 2019/01/08 09:29:34 fulford Exp $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-C) ttd=$2;shift 2;;
 		-c) config=$2;shift 2;;
 		-d) debug=:;set -x;shift;;
+		-s) sort=0;shift;;
 		-v) verbose=:;shift;;
 		-V) echo "$cmd $ver";exit;;
-		 *) id=$1;shift;;
+		 *) sites="$sites $1";shift;;
 	esac
 done
-[ -z "$id" ]&&{ echo "syntax: $syntax" >&2;exit 1;}
+[ -z "$sites" ]&&{ echo "syntax: $syntax" >&2;exit 1;}
 [ `id -u` -eq 0 ] &&{ echo "$cmd: Cannot run as root user.">&2;exit 1 ;}
 config=${config:-"/usr/local/etc/webv.cf"}
-[ -f "$config" ]||{ echo "$cmd: $config not found">&2;exit 1;}
+[ -f "$config" ]||{ echo "$cmd: $config not found">&2;exit 1 ;}
 
-eval `sed -ne "/^$id:/,/^$/{
-	/^[ \t][^#]*/p
-}" $config`
-
-[ -z "$URI" ] &&{ echo "$cmd: No URI for $id in $config";exit 1;}
-
-days=`expr \`date +%d\` - 1`
-hour=`date +%H`
-mins=`date +%M`
-dhrs=`bc<<- .
-	scale=2
-	$hour + ($mins/60)
-.`
-# total hours elapsed in month
-teh=`echo "scale=2;($days * 24 ) + $dhrs"|bc`
+tmp=/tmp/webv$$
 
 # total days in full month
-td=`cal \`date +"%m %Y"\`|awk 'NF {DAYS=$NF} END {print (DAYS)}'`
+Days=`cal \`date +"%m %Y"\` | awk 'NF {DAYS=$NF} END {print (DAYS)}'`
 
-# total hours in full month
-tmh=`bc<<- .
-	scale=2;$td * 24
-.`
-#[ $tmh -eq 0 ] && tmh=1
+# total mins in full month
+Mins=`bc<<- .
+	scale=2
+	$Days * 24 * 60
+	.
+`	
+[ $verbose ] &&{
+	printf "%30s %10s %9s %8s\n" "Website" "Visitors" "Average" "Prediction"
+}
 
+for site in $sites ;do
+	eval `sed -ne "/^$site:/,/^$/{
+			/^[ \t][^#]*/p
+		}" $config
+	      `
+	[ -z "$LOC" ] &&{
+       		echo "$cmd: No LOC for $site in $config" >&2
+		exit 1
+	}
+	[ -z "$STATSRVR" ] &&{
+       		echo "$cmd: No STATSRVR for $site in $config" >&2
+		exit 1
+	}
+	[ -z "$URI" ] &&{
+       		echo "$cmd: No URI for $site in $config" >&2
+		exit 1
+	}
 
-if [ ! $ttd ]; then
-	ttd=`wget -qO - $URI|
-		sed -ne '/Viewed traffic/s/[^0-9]*\([0-9,]*\).*/\1/p'|
-		sed -e 's/,//'`
-fi
+	read -r eDays eHrs eMins <<- .
+		$(date +"%d %H %M")
+	.
+	toteMins=`bc <<- .
+		$eDays * 24 * 60
+		.
+	`
+	toteMins=`bc <<- .
+		$eHrs *  60 + $toteMins
+		.
+	`
+	toteMins=`bc <<- .
+		scale=2
+		$eMins + $toteMins
+		.
+	`
+	[ ! $ttd ] &&{
+	  if wget --spider -q $STATSRVR$LOC ;then
+		ttd=`wget -qO - $STATSRVR$LOC |
+			sed -ne '/Viewed traffic/s/[^0-9]*\([0-9,]*\).*/\1/p'|
+			sed -e 's/,//'
+		`
+	  else
+		error=$?
+		echo "$cmd: $STATSRVR$LOC not available.">&2
+		exit $error
+	  fi
+	}
+	[ ! $ttd ] &&{
+		echo "$cmd: stats at $URI not found" >&2
+		continue
+	}
+	
+	ave=`bc <<- .
+		scale=4
+		$ttd / $toteMins
+		.
+	`
+	perDay=`bc <<- .
+		scale=3
+		$ave * 60 * 24 
+		.
+	`
 
-if [ "$verbose" ];then
-	echo $ttd |
-		awk -v id=$id '{
-		printf "%7s %s %4i  %s %4.1f  %s %5.f\n",id,"- Visitors so far:",$1,"Ave:",$1/'$teh',"Prediction:",$1/'$teh'*'$tmh'}'
+	predn=`bc <<- .
+		scale=3
+		$ave * $Mins
+		.
+	`
+	#home=`echo $URI|sed -ne 's/\([^\/]*\)\/.*$/\1/p'`
+	home=$URI
+	(( $(#home) > 30 )) && home="${home:0:27}..."
+	if [ "$verbose" ];then
+		printf "%30s %8i %10.2f %8.0f\n" $home $ttd $perDay $predn
+	else
+		printf "%30s %3i %4.2f %4.0f\n" $home $ttd $perDay $predn
+	fi
+	unset ttd URI LOC STATSRVR 
+done >$tmp 
+if [ $sort ];then
+	sort  -n -r -k3 <$tmp
 else
-	echo $ttd |
-		awk '{
-		  printf "%3i %4.1f %3.f\n",$1,$1/'$teh',$1/'$teh'*'$tmh'}'
+	cat $tmp
 fi
+[ -f $tmp ] && rm $tmp
+	
